### ISSUE TITLE
Error if no `.github` folder exists

### ISSUE THREAD

**Issue by CloutKhan** [Skenvy/dependabot-linguist#13]
### Operating System

Windows

### What version of dependabot-linguist did the issue happen on (either the tag, commit hash, or semver)?

`0.212.1`

### What semver version of the Ruby runtime did the issue happen on?

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

### What were you doing (steps to reproduce the bug)?

`::Dependabot::Linguist::DependabotFileValidator.commit_new_config`

### What actually happened as a result?

No such file or directory @ rb_sysopen - /<another-internal-path>/.github/dependabot.yml (Errno::ENOENT)

### What did you expect to happen?

The file to be written.

### If you have a stack trace, please add it here.

        3: from /<internal-path>/vendor/bundle/ruby/2.7.0/gems/dependabot-linguist-0.212.1/lib/dependabot/linguist/dependabot_file_validator.rb:216:in `commit_new_config'
        2: from /<internal-path>/vendor/bundle/ruby/2.7.0/gems/dependabot-linguist-0.212.1/lib/dependabot/linguist/dependabot_file_validator.rb:205:in `write_new_config'
        1: from /<internal-path>/vendor/bundle/ruby/2.7.0/gems/dependabot-linguist-0.212.1/lib/dependabot/linguist/dependabot_file_validator.rb:205:in `open'
/<internal-path>/vendor/bundle/ruby/2.7.0/gems/dependabot-linguist-0.212.1/lib/dependabot/linguist/dependabot_file_validator.rb:205:in `initialize': No such file or directory @ rb_sysopen - /<another-internal-path>/.github/dependabot.yml (Errno::ENOENT)

### Anything else you feel useful to add?

The issue is `File.open("#{@repo.path.delete_suffix("/.git/")}/#{dependabot_file_path}", "w")` on https://github.com/Skenvy/dependabot-linguist/blob/main/lib/dependabot/linguist/dependabot_file_validator.rb#L205 -- not creating the full path if it doesn't already exist. It works to create the file if the `~/.github/` folder already exists, but won't "full" path the file when creating it.

**Comment by CloutKhan** [comment]
```ruby
def write_new_config
  full_file_path = "#{@repo.path.delete_suffix("/.git/")}/#{dependabot_file_path}"
  FileUtils.mkdir_p File.dirname(full_file_path)
  File.open(full_file_path, "w") { |file| file.write(new_config.to_yaml) } if new_config != existing_config
end
```
